#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "📚 Claude Code PM - Project Management System"
echo "============================================="
echo ""
echo "🎯 Quick Start Workflow"
echo "  1. /ccpm:prd-new <name>        - Create a new PRD"
echo "  2. /ccpm:prd-parse <name>      - Convert PRD to epic"
echo "  3. /ccpm:epic-decompose <name> - Break into tasks"
echo "  4. /ccpm:github-sync           - Push to GitHub"
echo "  5. /ccpm:epic-start <name>     - Start parallel execution"
echo ""
echo "📄 PRD Commands"
echo "  /ccpm:prd-new <name>     - Launch brainstorming for new product requirement"
echo "  /ccpm:prd-parse <name>   - Convert PRD to implementation epic"
echo "  /ccpm:prd-list           - List all PRDs"
echo "  /ccpm:prd-edit <name>    - Edit existing PRD"
echo "  /ccpm:prd-status         - Show PRD implementation status"
echo ""
echo "📚 Epic Commands"
echo "  /ccpm:epic-decompose <name> - Break epic into task files"
echo "  /ccpm:epic-oneshot <name>   - Decompose and sync in one command"
echo "  /ccpm:epic-list             - List all epics"
echo "  /ccpm:epic-show <name>      - Display epic and its tasks"
echo "  /ccpm:epic-status [name]    - Show epic progress"
echo "  /ccpm:epic-close <name>     - Mark epic as complete"
echo "  /ccpm:epic-edit <name>      - Edit epic details"
echo "  /ccpm:epic-refresh <name>   - Update epic progress from tasks"
echo "  /ccpm:epic-start <name>     - Setup worktree for epic work"
echo "  /ccpm:epic-parallel [name]  - Launch parallel agents for tasks"
echo ""
echo "📝 Task Commands"
echo "  /ccpm:task-add [epic] <name> [opts] - Add task (to epic or backlog)"
echo "  /ccpm:task-start <epic> <num>       - Start working on task"
echo "  /ccpm:task-close <epic> <num>       - Complete task"
echo "  /ccpm:task-show <epic> <num>        - Show task details"
echo ""
echo "📝 Issue Commands"
echo "  /ccpm:issue-show <num>      - Display issue and sub-issues"
echo "  /ccpm:issue-status <num>    - Check issue status"
echo "  /ccpm:issue-start <num>     - Begin work with specialized agent"
echo "  /ccpm:issue-close <num>     - Mark issue as complete"
echo "  /ccpm:issue-reopen <num>    - Reopen closed issue"
echo "  /ccpm:issue-edit <num>      - Edit issue details"
echo "  /ccpm:issue-analyze <num>   - Analyze for parallel work streams"
echo ""
echo "🔄 Workflow Commands"
echo "  /ccpm:task-next               - Show next priority tasks"
echo "  /ccpm:status             - Overall project dashboard"
echo "  /ccpm:standup            - Daily standup report"
echo "  /ccpm:blocked            - Show blocked tasks"
echo "  /ccpm:in-progress        - List work in progress"
echo ""
echo "🔗 Sync Commands"
echo "  /ccpm:github-sync        - Full bidirectional sync with GitHub"
echo "  /ccpm:import <issue>     - Import existing GitHub issues"
echo ""
echo "🔧 Maintenance Commands"
echo "  /ccpm:validate           - Check system integrity"
echo "  /ccpm:clean              - Archive completed work"
echo "  /ccpm:search <query>     - Search across all content"
echo ""
echo "⚙️  Setup Commands"
echo "  /ccpm:init               - Install dependencies and configure GitHub"
echo "  /ccpm:help               - Show this help message"
echo ""
echo "💡 Tips"
echo "  • Use /ccpm:task-next to find available work"
echo "  • Run /ccpm:status for quick overview"
echo "  • Epic workflow: prd-new → prd-parse → epic-decompose → epic-sync"
echo "  • View README.md for complete documentation"

exit 0
